import OperatorKernelO6.Kernel
import OperatorKernelO6.Meta.Meta
import OperatorKernelO6.Meta.Termination
-- import OperatorKernelO6.Meta.Arithmetic
-- import OperatorKernelO6.Meta.Equality
-- import OperatorKernelO6.Meta.Godel
-- import OperatorKernelO6.Meta.Normalize
-- import OperatorKernelO6.Meta.FixedPoint
-- import OperatorKernelO6.Meta.Confluence
-- import OperatorKernelO6.Meta.ProofSystem

open OperatorKernelO6
open MetaSN
